using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using static Microsoft.CodeAnalysis.CSharp.SyntaxFactory;

namespace SampSharp.SourceGenerator.SyntaxFactories;

/// <summary>
/// Creates trivia syntax.
/// </summary>
public static class TriviaFactory
{
    public static SyntaxTrivia AutoGeneratedComment()
    {
        return Comment("// <auto-generated />");
    }
    
    public static SyntaxTrivia NullableEnable()
    {
        return Trivia(
            NullableDirectiveTrivia(
                Token(SyntaxKind.EnableKeyword),
                true));
    }
    public static SyntaxTrivia NullableDisable()
    {
        return Trivia(
            NullableDirectiveTrivia(
                Token(SyntaxKind.DisableKeyword),
                false));
    }
}