using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace SashManaged.SourceGenerator
{
    [Generator]
    public class OpenMpEventHandlerCodeGen : IIncrementalGenerator
    {
        public void Initialize(IncrementalGeneratorInitializationContext context)
        {
            var structPovider = context.SyntaxProvider.CreateSyntaxProvider(predicate: IsIfaceStub, transform: GetEventHandlerDeclaration).WithTrackingName("Syntax");

            context.RegisterSourceOutput(structPovider, (ctx, node) =>
            {
                if (node == null)
                {
                    return;
                }

                ctx.AddSource(node.Symbol.Name + ".g.cs", SourceText.From(Process(node), Encoding.UTF8));
            });
        }
        
        private static bool IsIfaceStub(SyntaxNode syntax, CancellationToken _) =>
            syntax is InterfaceDeclarationSyntax
            {
                AttributeLists.Count: > 0
            };
        
        private static EventHandlerDecl GetEventHandlerDeclaration(GeneratorSyntaxContext ctx, CancellationToken cancellationToken)
        {
            var declaration = (InterfaceDeclarationSyntax)ctx.Node;
            if (ctx.SemanticModel.GetDeclaredSymbol(declaration, cancellationToken) is not { } symbol)
                return null;
            
            if (!symbol.HasAttribute(Constants.EventHandlerAttributeFQN))
                return null;
            
            var members = symbol.GetMembers()
                .OfType<IMethodSymbol>()
                .ToList();

            return new EventHandlerDecl(symbol, declaration, members);
        }

        private static string Process(EventHandlerDecl node)
        {
            var handlerName = node.Symbol.Name.Substring(1);
            var dispatcherName = $"IEventDispatcher_{handlerName}";

            var sb = new StringBuilder();

            
            sb.AppendLine($$"""
                            /// <auto-generated />

                            namespace {{node.Symbol.ContainingNamespace.ToDisplayString()}}
                            {
                                internal class {{node.Symbol.Name}}_Handler : SashManaged.BaseEventHandler<{{node.Symbol.Name}}>
                                {
                                
                            """);
            
            // all members...
            foreach (var method in node.Members)
            {
                sb.AppendLine($$"""
                                        [System.Runtime.InteropServices.UnmanagedCallersOnly(CallConvs = new[] { typeof(System.Runtime.CompilerServices.CallConvStdcall) })]
                                        private static {{method.ReturnType.ToDisplayString()}} {{method.Name}}({{Common.ParameterAsString(method.Parameters)}})
                                        {
                                            {{(!method.ReturnsVoid ? "return " : "")}}Active?.{{method.Name}}({{Common.GetForwardArguments(method)}});
                                        }
                                        
                                """);
            }

            sb.AppendLine($$"""
                                    {{Common.DllImportAttribute("SampSharp")}}
                                    private static extern unsafe nint {{handlerName}}Impl_create(
                            """);

            var count = 0;
            foreach (var method in node.Members)
            {
                sb.Append("delegate* unmanaged[Stdcall]<");

                sb.Append(string.Join(", ", method.Parameters.Select(x => $"{Common.RefArgumentString(x.RefKind)}{x.Type.ToDisplayString()}")));

                if (method.Parameters.Length > 0)
                {
                    sb.Append(", ");
                }

                sb.AppendLine($"{method.ReturnType.ToDisplayString()}> _{method.Name}{(++count != node.Members.Count ? ", " : "")}");
            }

            sb.AppendLine($$"""
                                    );
                                    
                                    private {{node.Symbol.Name}}_Handler({{node.Symbol.Name}} handler, nint handle) : base(handler, handle)
                                    {
                                    }
                            
                                    {{Common.DllImportAttribute("SampSharp")}}
                                    private static extern void {{handlerName}}Impl_delete(nint ptr);
                                    
                                    protected override void Delete()
                                    {
                                        {{handlerName}}Impl_delete(Handle);
                                    }
                                    
                                    public static unsafe {{node.Symbol.Name}}_Handler Activate({{node.Symbol.Name}} handler)
                                    {
                                        if (Active == handler)
                                        {
                                            return ({{node.Symbol.Name}}_Handler)ActiveHandler!;
                                        }
                                    
                                        ThrowIfActive();
                                    
                                        var handle = {{handlerName}}Impl_create({{string.Join(", ", node.Members.Select(x => $"&{x.Name}"))}});
                                        return new {{node.Symbol.Name}}_Handler(handler, handle);
                                    }
                                }
                            """);

            sb.AppendLine($$"""
                                {{Constants.SequentialStructLayoutAttribute}}
                                {{node.TypeDeclaration.Modifiers}} struct {{dispatcherName}} : SashManaged.OpenMp.IEventDispatcher<{{node.Symbol.Name}}>
                                {
                                    private readonly nint _data;
                                    
                                    {{Common.DllImportAttribute("SampSharp")}}
                                    private static extern bool {{dispatcherName}}_addEventHandler({{dispatcherName}} dispatcher, nint handler, EventPriority priority);
                                    
                                    {{Common.DllImportAttribute("SampSharp")}}
                                    private static extern bool {{dispatcherName}}_removeEventHandler({{dispatcherName}} dispatcher, nint handler);
                                    
                                    {{Common.DllImportAttribute("SampSharp")}}
                                    private static extern bool {{dispatcherName}}_hasEventHandler({{dispatcherName}} dispatcher, nint handler, out EventPriority priority);
                                    
                                    public bool AddEventHandler({{node.Symbol.Name}} handler, EventPriority priority = EventPriority.Default)
                                    {
                                        var active = {{node.Symbol.Name}}_Handler.Activate(handler);
                                    
                                        if (!{{dispatcherName}}_addEventHandler(this, active.Handle, priority))
                                        {
                                            return false;
                                        }
                                    
                                        var dispatcher = this;
                                        active.Disposing += (sender, e) => dispatcher.RemoveEventHandler(handler);
                                    
                                        return true;
                                    }
                                    
                                    public bool RemoveEventHandler({{node.Symbol.Name}} handler)
                                    {
                                        if ({{node.Symbol.Name}}_Handler.Active != handler)
                                        {
                                            return false;
                                        }
                                    
                                        return {{dispatcherName}}_removeEventHandler(this, {{node.Symbol.Name}}_Handler.ActiveHandle!.Value);
                                    }
                                    
                                    public bool HasEventHandler({{node.Symbol.Name}} handler, out EventPriority priority)
                                    {
                                        if ({{node.Symbol.Name}}_Handler.Active != handler)
                                        {
                                            priority = default;
                                            return false;
                                        }
                                    
                                        return {{dispatcherName}}_hasEventHandler(this, {{node.Symbol.Name}}_Handler.ActiveHandle!.Value, out priority);
                                    }
                                }
                            }
                            """);


            return sb.ToString();
        }

        private class EventHandlerDecl(ISymbol symbol, InterfaceDeclarationSyntax typeDeclaration, List<IMethodSymbol> members)
        {
            public ISymbol Symbol { get; } = symbol;
            public InterfaceDeclarationSyntax TypeDeclaration { get; } = typeDeclaration;
            public List<IMethodSymbol> Members { get; } = members;
        }
    }
}
